name: sdr_printer_manager
description: "Aplikasi pengelola koneksi printer Bluetooth POS terintegrasi dRetail Mart."
publish_to: 'none'

version: 1.0.3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  print_bluetooth_thermal:
    path: ./packages/print_bluetooth_thermal
  shared_preferences: ^2.3.2
  permission_handler: ^12.0.3
  network_info_plus: ^8.2.1
  file_picker: ^12.0.0
  image: ^4.2.0
  pdfx: ^2.6.0
  curved_navigation_bar: ^1.0.6
  share_plus: ^13.3.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/